spring:
  application:
    name: virtual-pet-app
  profiles:
    active: dev

  # JSON/Jackson Configuration
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Transaction Configuration
  transaction:
    default-timeout: 30s

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      cache-null-values: false
    cache-names:
      - users
      - pets
      - activities

# Server Configuration (default)
server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# Custom Virtual Pet Configuration
virtual-pet:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"
      - "http://127.0.0.1:5173"
      - "http://127.0.0.1:3000"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

  game:
    max-pets-per-user: 5
    starting-coins: 500
    level-up-experience: 100
    max-level: 50

  degradation:
    hunger-rate: 2
    happiness-rate: 1
    health-rate: 0.5
    energy-regen-rate: 5

  intervals:
    degradation-check: "0 */5 * * * *"
    status-update: "0 */1 * * * *"

  notifications:
    low-stat-threshold: 20
    critical-threshold: 10

# Default Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Default Logging Configuration
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    com.snowleopard.virtual_pet: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.mongodb.driver: WARN
    redis.clients.jedis: WARN