# Fixed application-dev.yml
server:
  port: 8088

spring:
  application:
    name: virtual-pet-dev

  # Development MongoDB (local)
  data:
    mongodb:
      uri: mongodb://localhost:27017/virtualpet_dev
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 1

# Development logging
logging:
  level:
    com.snowleopard.virtual_pet: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development settings
virtual-pet:
  game:
    max-pets-per-user: 10
    starting-coins: 1000
    level-up-experience: 50

  degradation:
    hunger-rate: 1
    happiness-rate: 1
    energy-regen-rate: 10

# Enable all actuator endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always